# Generated by Django 4.2.7 on 2026-05-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='planned', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounts.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['-date', 'start_time'],
                'unique_together': {('employee', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Время прихода')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Время ухода')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_late', models.BooleanField(default=False, verbose_name='Опоздание')),
                ('is_early_departure', models.BooleanField(default=False, verbose_name='Ранний уход')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='schedule.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Запись о рабочем времени',
                'verbose_name_plural': 'Записи о рабочем времени',
                'ordering': ['-created_at'],
            },
        ),
    ]
